### ISSUE TITLE
Git clone issue

### ISSUE THREAD

**Issue by libra10042** [kho903/java-question#1]
![image](https://user-images.githubusercontent.com/46278436/193410977-e47fcdb3-505c-4dd8-9569-6177e8ca5eca.png)

mac에서는 사용이 가능하지만 

windows에서는 아래와 같이 9가지 문자열은 파일명으로 지정할 수 없다고 하네요. 
```
\ / : * ? " < > |
```
![image](https://user-images.githubusercontent.com/46278436/193411050-8b325af1-667e-4f29-8172-eba9d8967b55.png)

[참고](https://young-cow.tistory.com/47)

01. 프로그래밍이란 무엇인가?  파일명 수정 부탁드립니다!

**Comment by kho903** [comment]
수정완료입니다.
